export const WEBSITE_TEMPLATES = [
  {
    id: "seo-pro",
    name: "SEO Pro",
    description: "Full business landing page - hero, services, products, blog, contact & cart.",
    preview: "seo",
    accent: "#2e8b57",
    isNew: true,
  },
  {
    id: "business-pro",
    name: "Business Pro",
    description: "Clean corporate profile with services, experience, and contact CTA.",
    preview: "business",
    accent: "#1e40af",
    isNew: true,
  },
  {
    id: "studio-pro",
    name: "Studio Pro",
    description: "Bold creative layout - sidebar profile with skills & portfolio highlights.",
    preview: "studio",
    accent: "#7c3aed",
    isNew: true,
  },
  {
    id: "architecture-pro",
    name: "Architecture Pro",
    description: "Elegant architecture portfolio with projects, design philosophy, and consultation CTA.",
    preview: "architecture",
    accent: "#c2410c",
    isNew: true,
  },
  {
    id: "interior-pro",
    name: "Interior Pro",
    description: "Warm interior design portfolio with moodboards, services, and contact sections.",
    preview: "interior",
    accent: "#db2777",
    isNew: true,
  },
  {
    id: "developer-pro",
    name: "Developer Pro",
    description: "Fast-paced developer portfolio with stack, projects, experience, and CTA.",
    preview: "developer",
    accent: "#2563eb",
    isNew: true,
  },
  {
    id: "it-engineer-pro",
    name: "IT Engineer Pro",
    description: "Reliable systems-focused portfolio for IT support, operations, and infrastructure roles.",
    preview: "it-engineer",
    accent: "#0f766e",
    isNew: true,
  },
  {
    id: "modern",
    name: "Modern",
    description: "Classic portfolio with sticky nav and gradient hero.",
    preview: "modern",
    accent: "#4f46e5",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Typography-focused, elegant single-column layout.",
    preview: "minimal",
    accent: "#0f172a",
  },
  {
    id: "creative",
    name: "Creative",
    description: "Split-screen creative portfolio with bold cards.",
    preview: "creative",
    accent: "#db2777",
  },
];

export const TEMPLATE_IDS = WEBSITE_TEMPLATES.map((t) => t.id);
