name: Careerandnaukari Deployment
on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /var/www/careerandnaukari
          git fetch origin main
          git reset --hard origin/main
          git pull origin main
          
          cd frontend
          
          npm install --force
          npm run build

          cd ../backend
          npm install

          cd ..
          pm2 restart all || pm2 startOrReload pm2.yml
        env:
          CI: false

# name: Careerandnaukari Deployment
# on: [push]

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Deploy
#         run: |
#           cd /var/www/careerandnaukari
#           git fetch origin main
#           git reset --hard origin/main
#           git pull origin main
          
#           # --- Frontend Section ---
#           cd frontend
          
#           rm -rf .next
#           rm -rf node_modules
#           rm -f package-lock.json

#           # ફ્રેશ ઇન્સ્ટોલ
#           npm install --force
          
#           # આ પેકેજને મેન્યુઅલી નાખો
#           npm install @tailwindcss/postcss postcss tailwindcss --save

#           # મહત્વનું: Turbopack વગર બિલ્ડ કરો (Webpack વાપરો)
#           # આનાથી CSS એરર સોલ્વ થઈ જશે
#           npx next build --no-turbo

#           # --- Backend Section ---
#           cd ../backend
#           npm install

#           # --- PM2 Restart Section ---
#           cd ..
#           pm2 restart all || pm2 startOrReload pm2.yml
#           pm2 save
          
#         env:
#           CI: false
#           NODE_ENV: production